FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

WORKDIR /app
COPY ./app ./app
COPY ./tests ./tests
COPY ./requirements.txt ./
RUN pip install -r requirements.txt
RUN chmod +x ./tests/run.sh


CMD [ "./tests/run.sh" ]
